### ISSUE TITLE
Index of Multiple Deprivation for GB

### ISSUE THREAD

**Issue by athrado** [nestauk/asf_exploration#12]

**Comment by danlewis85** [comment]
Unfortunately the devolved nations all have different IMD statistics. Scotland in particular is out of sync with England and Wales.

There is a useful England and Wales combined score for the IMD income and employment domains: https://www.gov.uk/government/statistics/indices-of-deprivation-2019-income-and-employment-domains-combined-for-england-and-wales

Alternatives for GB-level deprivation might include doing something simple for GB based on census data e.g. townsend/carstairs index, however these stats are old and don't necessarily include items that reflect modern-day deprivation so well (e.g. car ownership).

A review of approaches to this problem might turn up some useful resources for GB that I'm not aware of, so please share if you find anything promising.

**Comment by athrado** [comment]
Thanks, I'm aware. See also [README](https://github.com/nestauk/asf_exploration/tree/12_imd_for_gb/imd_for_gb). This code and data is only meant as reference for future projects.
